Printercurement\EprocurementBundle\Entity\CatalogStructure:
    type: entity
    table: catalog_structure
    id:
        node_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        parent_node_id:
            type: integer
            column: parent_node_id
            nullable: true
        catalog_id:
            type: integer
            column: catalog_id
        company_id:
            type: integer
            column: company_id
        user_id:
            type: integer
            column: user_id
    lifecycleCallbacks: {  }
