Printercurement\EprocurementBundle\Entity\Catalog:
    type: entity
    table: catalog
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '45'
        created_by:
            type: integer
            column: created_by
        dt_created:
            type: datetime
            column: dt_created
    lifecycleCallbacks: {  }
