core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

catalog:
    resource: "@CatalogBundle/Resources/config/routing.yml"
    prefix:   /catalogs

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
