core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

esourcing:
    resource: "@EsourcingBundle/Resources/config/routing.yml"
    prefix:   /

eprocurement:
    resource: "@EprocurementBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
