core_user:
    resource: "@CoreBundle/Resources/config/routing/user.yml"
    prefix:   /user

user_show:
    path:     /user/{id}/show
    defaults: { _controller: "CoreBundle:User:show" }

new_user:
    path:     /user/new
    defaults: { _controller: "CoreBundle:User:new" }

user_create:
    path:     /user/create
    defaults: { _controller: "CoreBundle:User:create" }
    methods:  POST

core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: CoreBundle:Security:login }

login_check:
    path:     /login_check

logout:
    path:     /logout

admin:
    path:     /admin
    defaults: { _controller: CoreBundle:Admin:index }

home:
    path:     /home
    defaults: { _controller: CoreBundle:Index:home }
