core_user:
    resource: "@CoreBundle/Resources/config/routing/user.yml"
    prefix:   /user

core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: CoreBundle:Security:login }

login_check:
    path:     /login_check

logout:
    path:     /logout
