core_admin:
    resource: "@CoreBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Index:index }

home:
    path:     /home
    defaults: { _controller: CoreBundle:Index:home }

login:
    path:     /login
    defaults: { _controller: CoreBundle:Security:login }

login_check:
    path:     /login_check

logout:
    path:     /logout



