catalogs:
    path:     /
    defaults: { _controller: CatalogBundle:Catalogs:index }

get_catalogs:
    path:     /get_catalogs
    defaults: { _controller: CatalogBundle:Catalogs:getCatalogs }
    requirements: { _format: json }

catalog_index:
    path:     /{id}/{urlName}
    defaults: { _controller: CatalogBundle:Catalog:index }

catalog_create:
    path: /create
    defaults: { _controller: CatalogBundle:Catalog:create }

catalog_do_create:
    path: /do_create
    defaults: { _controller: CatalogBundle:Catalog:doCreate }
    requirements: { _method: post }

catalog_catalogs:
    path: /show
    defaults: { _controller: CatalogBundle:Catalogs:catalogs }