eprocurement_homepage:
    path: /eprocurement
    defaults: { _controller: EprocurementBundle:Index:index }

eprocurement_catalogs:
    path: /eprocurement/catalogs
    defaults: { _controller: EprocurementBundle:Catalog:index }

eprocurement_catalogs_get:
    path: /eprocurement/catalogs/get
    defaults: { _controller: EprocurementBundle:Catalog:getCatalogs }
    requirements: { _format: json }

eprocurement_catalog:
    path: /eprocurement/catalog/{id}/{urlName}
    defaults: { _controller: EprocurementBundle:Catalog:getCatalog }

eprocurement_catalog_create:
    path: /eprocurement/catalog/create
    defaults: { _controller: EprocurementBundle:Catalog:create }

eprocurement_articles:
    path: /eprocurement/articles
    defaults: { _controller: EprocurementBundle:Article:index }

eprocurement_article:
    path: /eprocurement/article/{id}/{urlName}
    defaults: { _controller: EprocurementBundle:Article:getArticle }

eprocurement_articles_get:
    path: /eprocurement/articles/get/{catalogNodeId}
    defaults: { _controller: EprocurementBundle:Article:getArticles }
    requirements: { _format: json }

eprocurement_article_create:
    path: /eprocurement/article/create
    defaults: { _controller: EprocurementBundle:Article:create }

eprocurement_cart_widget:
    path: /eprocurement/cart/widget
    defaults: { _controller: EprocurementBundle:Cart:widget }
